#!/bin/sh

ARGS="${@}"
readonly ARGS

require_please() {
    command which -s "please"
}

main() {

    if test $(require_please)
    then
        echo please
        command please ${ARGS}
    else
        command sudo ${ARGS}
    fi

}

main ${ARGS}
