#!/bin/sh

main() {

    local files IFS
    files=""
    IFS='
'

    for file in $(dirname "${1}")/*
    do
        ext="${file##*.}"
        case "${ext}" in
            webm|mp4|wmv|flv|mkv|mov)
                files="${files}
${file}"
                ;;
        esac
    done

    mpv ${files}
}


main "${@}"
