#!/bin/sh

ARGS="${@}"
readonly ARGS

require_please() {
    which please
}

main() {

    require_please 1> /dev/null
    if test 0 -eq $?
    then
        echo using please instead of sudo
        please ${ARGS}
    else
        sudo -E ${ARGS}
    fi

}

main ${ARGS}
