#!/bin/sh

## https://gist.github.com/7984374.git

pomdfload::help() {
    echo "Usage: `basename $0` FILE [FILE...]"
    exit 1
}

pomfload::upload() {
    for f in "$@"; do
        d=$(curl --silent --show-error --progress-bar -F files[]="@$f" http://pomf.se/upload.php | jq -c -r '.files[0].url')

        if [ $# -gt 1 ]; then
            # Apparently some builtin echos haet -n.
            /bin/echo -n "$f: "
        fi
        echo "http://a.pomf.se/$d"
    done
}

pomfload::main() {
    if [ $# -lt 1 ]; then
        help
    fi

    if [ $# -gt 1 ]; then
        # Apparently some builtin echos haet -n.
        echo "$# files specified"
    fi

    pomfload::upload "$@"
}

pomfload::main "$@"
